
looking at a Loan Data from a European Central Bank. Our job as Data Analysts is to make the dataset ready, that is Gather,clean and preprocess it and pass it to the Data Scientists who would build a Credit Risk Model.

We will of course note down all the changes we are making to the dataset in a documentation file - which would be invaluable to the Data Scientists or whoever would be working with the dataset after us.  

Our major role in the dataset would be to examine the data, import the data, split the data.

### Project:

You are working as  Data Analyst in a Data Science Team of a Central Bank in Europe. Your Team has been tasked to create a `Credit Risk Model(CRM)` which estimates the probability of default for every personal account.  Therefore the following terms would be evaluated on the dataset, `Probability of default, Recovery rate, Credit Risk Modelling`. They have asked us to take the datasets and prepare it for the models they intend to run. They have provided details on the columns in the dataset, and a set of rules we should follow during preprocessing. Infact, the data cleaning and preprocessing task, represent the essence of the data cleaning job. Here are some guided steps:

- The Loan data is a sample from a larger dataset that belongs to an afiliate bank based in the united states. Therefore, the default currenccy is in dollars  so we need to provide their Euro Equivalents.
- Every categorical variable must be quantified. That is, we need to change any text column into numbers.
- For the Issue date, we can split them into months. For others, we only care if they provide a positive or negative connotations. So we would be turning them into dummy variables that holds either 0 or 1.

Finally, When measuring credit worthiness, we need to be extremely risk-averse and distrustful of any unavailable data. Thats why the consensus in the field is that missing information suggests foul play  because loan applications are self reporting. To elaborate, since candidates fill their loan applications manually, there is an incentive to withold information which can lower their chances to get a loan. Therefore, if the information isn't availble, we would just assume the worst

### Import the Packages

In [1]:
#import numpy and standardize in case of scientific notations
import numpy as np
np.set_printoptions(suppress=True, linewidth=100, precision=2)

### Loading the dataset

In [2]:
raw_data_np=np.genfromtxt("C:\\Users\\USER\\Downloads\\loan-data.csv",
                          delimiter=',',
                         skip_header=1,
                          autostrip=True)
                       
                        
raw_data_np

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

### Checking for Missing Values

In [3]:
#check for the count of missing data
np.isnan(raw_data_np).sum()

88005

In [4]:
#lets create filler values for the dataset as well as a temporary mean.
temporary_fill=np.nanmax(raw_data_np).round(2)+1
temprorary_mean=np.nanmean(raw_data_np,axis=0).round(2)

C:\Users\USER\AppData\Local\Temp\ipykernel_340\3972857773.py:3: RuntimeWarning: Mean of empty slice
  temprorary_mean=np.nanmean(raw_data_np,axis=0).round(2)


Warnings do not stop codes from running, they only tell us that we might be overlooking somethings.
In this case, we might be having columns with only nan values in these cases we wont have a  mean for them.

In [5]:
#lets check for how many columns with missing values.  #call temporary mean
temprorary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

We have about 8  columns with missing data, or in this case text data. which are nans.

We would need to get the mins and maxs from the dataset. The head of Data Analytics has given iuis casting directions on how to go about filling missing values.

In [6]:
#create an array temporary stats variable to store the the min, mean and max for every column in raw_data_np
temporary_stats=np.array([np.nanmin(raw_data_np,axis=0),
                         np.nanmean(raw_data_np,axis=0),
                         np.nanmax(raw_data_np,axis=0)])
temporary_stats

C:\Users\USER\AppData\Local\Temp\ipykernel_340\3311710201.py:2: RuntimeWarning: All-NaN slice encountered
  temporary_stats=np.array([np.nanmin(raw_data_np,axis=0),
C:\Users\USER\AppData\Local\Temp\ipykernel_340\3311710201.py:3: RuntimeWarning: Mean of empty slice
  np.nanmean(raw_data_np,axis=0),
C:\Users\USER\AppData\Local\Temp\ipykernel_340\3311710201.py:4: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np,axis=0)])


array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

### Splitting the Dataset

We want to split the dataset into Text Data and Numeric Data.

To split the dataset, we first need to know which type of data belongs to which

######  splitting the columns

In [7]:
#string column. we can use the argwhere() to find the text columns.  make sure the ouput is a flattened 1d array
column_strings=np.argwhere(np.isnan(temprorary_mean)).squeeze()

In [8]:
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

To better understand the above, the default for .argwhere() is to find values different from 0, therefore, .isnan() returns True for values that are nan in the temporary mean. since True is different from 0, .argwhere() would return the indices of those column different from 0 or in this case strings. This would make up our text columns. The squeeze function converts the 2d output to a 1d array.

In [9]:
#string numeric
column_numeric=np.argwhere(np.isnan(temprorary_mean)==False).squeeze()

In [10]:
column_numeric

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

### Reimporting the Dataset

In [11]:
#string import
loan_data_strings=np.genfromtxt("C:\\Users\\USER\\Downloads\\loan-data.csv",
                        delimiter=',',
                        skip_header=1,
                        autostrip=True,
                        usecols=column_strings,
                        dtype=str)
                        
loan_data_strings

array([['15-May', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['15-Sep', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['15-Jun', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['15-Apr', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['15-Dec', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [12]:
#numeric import
loan_data_numeric=np.genfromtxt("C:\\Users\\USER\\Downloads\\loan-data.csv",
                        delimiter=',',
                        skip_header=1,
                        autostrip=True,
                        usecols=column_numeric,
                        filling_values=temporary_fill)
                        
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

### The names of the columns

We dont want to loose track of the columns we have so it is imperative we get the names of the columns we would be working on

In [13]:
#lets get the full header of the dataset
header_full=np.genfromtxt("C:\\Users\\USER\\Downloads\\loan-data.csv",
                        delimiter=',',
                        skip_footer=raw_data_np.shape[0],
                        autostrip=True,
                        dtype=str)
                        
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [14]:
#create two header names for strings and numeric data
header_strings,header_numeric=header_full[column_strings],header_full[column_numeric]

In [15]:
#call the header strings
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [16]:
#call header numeric
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### Creating checkpoints

Checkpoints in Jupyter Notebook are created to save the state of the notebook at a particular point in time. This can be useful for a number of reasons, such as:

- Recovering from crashes or errors: If your notebook crashes or you make an accidental change that you don't want, you can revert to a previous checkpoint.
- Undoing changes: If you make a change to your notebook that you don't like, you can revert to a previous checkpoint to undo the change.
- Comparing versions: If you're working on a long-running project, you can create checkpoints at different points in time to compare how your code has changed over time.
- Debugging issues: If you encounter a bug in your notebook, you can use checkpoints to isolate the problem. By comparing the state of the notebook at different checkpoints, you can identify which code changes led to the bug.

### Manipulating String Columns

In [17]:
#call the header strings
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [18]:
#the first item is issue_d we can rename it to issue date
header_strings[0]="issue_date"

In [19]:
#lets examine the data closelu and see what it looks like
loan_data_strings[:,0]

array(['15-May', '', '15-Sep', ..., '15-Jun', '15-Apr', '15-Dec'], dtype='<U69')

### Issue Date

In [20]:
#call the issue date column


we can see the issue date contains the first three letters of the month and the year accompanying it.

In [21]:
#call the unique vlues of the issue date column
np.unique(loan_data_strings[:,0])

array(['', '15-Apr', '15-Aug', '15-Dec', '15-Feb', '15-Jan', '15-Jul', '15-Jun', '15-Mar',
       '15-May', '15-Nov', '15-Oct', '15-Sep'], dtype='<U69')

In [22]:
#lets strip the -15 part from the column since they are all from the year 2015. 
np.chararray.strip(loan_data_strings[:,0],"15-")

chararray(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [23]:
#lets be sure the changes are permanent
loan_data_strings[:,0]=np.chararray.strip(loan_data_strings[:,0],"15-")

The output is better, howwver given that we are in Numpy, what we would usually need to do in our analysis, is to replace the months with integers. This approach will enable our data to take less memory as integers take less space than texts. Dont forget we have missing values as well

In [24]:
#to replace the months with numeric, we would first of all create an array with the months
months=np.array(["","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"])

In [25]:
#use a for loop to iterate through the issue date column and change the months to integer values
for i in range(13):
    loan_data_strings[:,0]=np.where(loan_data_strings[:,0]==months[i],
                                    i,
                                    loan_data_strings[:,0])

In [26]:
#call the unique vlues for the issue date
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

In [27]:
#replace the missing months with 0
loan_data_strings[:,0]=np.where(loan_data_strings[:,0]=="",
                               0,
                               loan_data_strings[:,0])

### Loan Status

In [28]:
#call the header_strings
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [29]:
#call the loan status column on loan_data_strings
loan_data_strings[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [30]:
#retrieve the unique values from this column
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [31]:
#lets get the number of unique values in the column
np.unique(loan_data_strings[:,1]).size

9

we would like to create dummy variables to replace each of the 9 individual elements, howwver we have been told regressions according to the probability of default, only cares if the candidate is in a stable financal condition or not. in otherwords, we are creating two groups to see if the loan condition is good or bad.

To put into context,

- Good: current,Fully paid, in Grace Period, Issued, Late(16-30 days)  - this is because they have defualted for less than a month and perhaps still waiting for their salaries before they could pay
- Bad: charged off, Default, Late(31-120 days), since we assume the worse, those with missing status will be considered as bad loan

In [32]:
#to do this, we can create a variable to store either the good or the bad. Ensure to write them as they appear
status_bad=np.array(['','Charged Off','Default','Late (31-120 days)'])

In [33]:
#use a where function and isin to store the valiues as 0 and 1. status_bad=0, else 1
loan_data_strings[:,1]=np.where(np.isin(loan_data_strings[:,1],status_bad),0,1)

In [34]:
loan_data_strings

array([['5', '1', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['0', '1', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['9', '1', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['6', '1', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['4', '1', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['12', '1', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### Term

In [35]:
#display the header_strings
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [36]:
#examine it by calling the column
loan_data_strings[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [37]:
#call the unique values for the column
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [38]:
#strip the months part from the values in the column
loan_data_strings[:,2]=np.chararray.strip(loan_data_strings[:,2]," months")
np.unique(loan_data_strings[:,2])

array(['', '36', '60'], dtype='<U69')

In [39]:
#lets make sure the column name is properly written. let it be term_months
header_strings[2]="term_months"
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [40]:
#use a where function to replace all the missing values to 60 months since we are assuming the worse
loan_data_strings[:,2]=np.where(loan_data_strings[:,2]=="",
                               60,
                               loan_data_strings[:,2])

### Grade and Sub Grade

In [41]:
#display the header strings
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [42]:
#examine the column on the loan_data
loan_data_strings[:,3]

array(['C', 'A', 'B', ..., 'A', 'D', 'A'], dtype='<U69')

In [43]:
#check for the distinct values  in thecolumn
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [44]:
#before we proceed further, lets examine the subgrade
loan_data_strings[:,4]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [45]:
#check for the distinct values  in the subgrade column
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

from what we can gather about the two columns, it means that for every element in the grade, there is an corresponding element in the  sub grade column numbered 1 to 5.
This theoretically makes the grade column redundant, however, this might not be true as we can use the grade column to fill for missing values in the sub grade column.

### Filling the Sub grade column

In [46]:
#use a for loop to   fill missing valuues in the subgrade column row wise, based on the the values in the grade column
for i in np.unique(loan_data_strings[:,3])[1]:
    loan_data_strings[:,4]=np.where((loan_data_strings[:,4]=="")& (loan_data_strings[:,3]==i),
                                                                   i+"5",
                                                                   loan_data_strings[:,4])

In [47]:
#check for the distinct values  in the subgrade column again
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [48]:
#lets check the number of times each values occur in the dataset
np.unique(loan_data_strings[:,4],return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([424, 285, 278, 239, 323, 592, 509, 517, 530, 553, 494, 629, 567, 586, 564, 423, 391, 267,
        250, 255, 223, 235, 162, 171, 139, 114,  94,  52,  34,  43,  16,  19,  10,   3,   7,   2],
       dtype=int64))

we see that the mising value occurs 9 times. Our dataset is 10000 rows. technically , we can afford to drop this columns and it wont hinder our analysis.
9 out of 10000 is insignificant. However, as credit risk analysts, we can use something else to fill this since we want to make sure we account for those that have defaulted in their loan payments. we can introduce another subgrade H1 hich is lower than even G5.

In [49]:
#fill the missing elemnts in the subgrade with H1
loan_data_strings[:,4]=np.where(loan_data_strings[:,4]=="",
                                "H1",
                               loan_data_strings[:,4])

### Deleting the grade Column

In [50]:
# use the np.delet to remove the grade column from the dataset
loan_data_strings=np.delete(loan_data_strings,3,axis=1)

In [51]:
#  call the third column fro  the loan data strings
loan_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

We see that the third column is now sub grade rather than grade

In [52]:
#remove the grade column from the header_strings
header_strings=np.delete(header_strings,3)

In [53]:
#when we display the 4th elemnt of the header, we see sub grade, rather than grade
header_strings[3]

'sub_grade'

### Converting the subgrade Column

In [54]:
#to convert the suub_grade_column to numbers, we can use the where function or a dictionary.
keys=list(np.unique(loan_data_strings[:,3]))

values=list(range(1,37))
dict_sub_grade=dict(zip(keys,values))

In [55]:
#althernative code to count the sub_grade column
np.unique(loan_data_strings[:,3]).shape[0]+1


37

In [56]:
#call  the dict sub grade variable
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [57]:
#use a loop to convert the elemnts of the sub grade to numeric elements
for i in np.unique(loan_data_strings[:,3]):
    loan_data_strings[:,3]=np.where(loan_data_strings[:,3]==i,
                                     dict_sub_grade[i],
                                     loan_data_strings[:,3])

In [58]:
#call np.unique of the subgrade column
np.unique(loan_data_strings[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification status 

In [59]:
#call header_strings to view the content of the verification status
header_strings[4]

'verification_status'

In [60]:
#examine the data on the loan data strings
loan_data_strings[:,4]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      dtype='<U69')

In [61]:
#call the unique values of the verification strings
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

For the missing values, we would assume it is no verified since we assume the worse.

for source verifed and verified, it represents loan applications which has investors backings. However, source verified has more  concrete backings. in this case we wppuld assume that the both are verified, and categorize them into one

In [62]:
#lets use the where function to convert the values to numeric.0 for unverified and missing values, 1 for sourceverified&verifie
loan_data_strings[:,4]=np.where((loan_data_strings[:,4]=="")|(loan_data_strings[:,4]=="Not Verified"),0,1)

### URL

In [63]:
#get the url column
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

we can see that the url address are mostly the same for each row, excpet for the loan id number at the end

In [64]:
#lets strip the url address for the url column
np.chararray.strip(loan_data_strings[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [65]:
#lets overwrite the changes made 
loan_data_strings[:,5]=np.chararray.strip(loan_data_strings[:,5],"https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [66]:
#recall that we had a column id before spitting the dataset.
#display header_full
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [67]:
#display the id column from the loan numeric
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

We can see that the ids are synonymous with the values above from the url column, the url column is in strings while the id is in floats

In [68]:
#lets cast them both to integers
loan_data_strings[:,5].astype(dtype=int)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [69]:
#cast the url to integers
loan_data_strings[:,5].astype(dtype=int)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [70]:
#we can use the array equal to check if they are both the same to be sure
np.array_equal(loan_data_numeric[:,0].astype(dtype=int),loan_data_strings[:,5].astype(dtype=int))

True

In [71]:
#lets delete the url column since it is the same with the id column from the numeric dataset.
loan_data_strings=np.delete(loan_data_strings,5,axis=1)

#also delete the url from the header_strings
header_strings=np.delete(header_strings,5)

In [72]:
#verify that you have deleted the ur column
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [73]:
#verify that you have deleted the column name from the header strings
header_strings[5]

'addr_state'

In [74]:
#verify the loan numeric
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [75]:
#verify the header numeric
header_numeric[0]

'id'

### State Address

In [76]:
#call the state address from the loan data strings
loan_data_strings[:,-1]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [77]:
# call the header name for the last column
header_strings[5]

'addr_state'

In [78]:
#lets rename it to state address
header_strings[5]="state_address"

In [79]:
#get the unique values from the state address
np.unique(loan_data_strings[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

we can see that these are the states in the united states. we also seem to have a missing value.  also, we would need to check if they are up to 50 states

In [80]:
#get the number of elemnts in the column
np.unique(loan_data_strings[:,5]).size

50

This means we have a state missing in the data, and the we must assume that the missing value represent the missing state in the column. The missing state is Iowa. we can say that this state was purposely left out as it must have been used as a baseline benchmark.

When doing research or analysis on a variable with many categories, it is normal to pick one as a  benchmark and include dummy variables for the rest.

In [81]:
#lets see the number of times they appear in the dataset
np.unique(loan_data_strings[:,5],return_counts=True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

since we cant make sense of this, lets  return the  above in descending order using the argsort function. Thus will return the indices that will sort the arrays


In [82]:
state_name,state_count=np.unique(loan_data_strings[:,5],return_counts=True)
state_count_sorted=np.argsort(-state_count)
state_name[state_count_sorted],state_count[state_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

Unsurprisingly, we see thatbthe highest loan applications are from wealthy states and populous states in the us.

We see that, we have 500 missing values which are larger than the 45 other states individually. Therefore, we have very little data for too many  states to examine each one individually.

If we assign a uunique value to each state, this would allow outliers to have too many infkuence on the coefficients. To elaborate, the more categries a variable has, the fewer data will be available for earch one.

To solve this problem, we need to group these states according to a certain characteristics, such as their geographical characteristics. 

Also, we would assign missing values with 0, to avoid creating a bias as well as causing outliers.

In [83]:
#lets take care of the missing data
loan_data_strings[:,5]=np.where(loan_data_strings[:,5]=="",
                               0,
                               loan_data_strings[:,5])

In [84]:
#create a state variable and store the names of the state in them
states_west = np.array(["WA", "OR", "CA", "NV", "ID", "MT", "WY", "UT", "CO", "AZ", "NM", "AK", "HI"])
states_south = np.array(["TX", "OK", "AR", "LA", "MS", "AL", "TN", "KY", "FL", "GA", "SC", "NC", "VA", "WV", "MD", "DE", "DC"])
states_midwest = np.array(["ND", "SD", "NE", "KS", "MN", "IA", "MO", "WI", "IL", "IN", "MI", "OH"])
states_east = np.array(["ME", "NH", "VT", "MA", "RI", "CT", "NJ", "NY", "PA"])


In [85]:
#use a where function to substitute for the regions and convert them to a numeric value
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5],states_west),1,loan_data_strings[:,5])
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5],states_south),2,loan_data_strings[:,5])
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5],states_midwest),3,loan_data_strings[:,5])
loan_data_strings[:,5]=np.where(np.isin(loan_data_strings[:,5],states_east),4,loan_data_strings[:,5])

In [86]:
#call the unique function on the the column
np.unique(loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

###   Converting to Numbers

In [87]:
#display the strings dataset
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [88]:
#convert the dataset from texts to strings
loan_data_strings.astype(dtype=int)

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [89]:
#lets overwrite the entire dataset to contain integer values
loan_data_strings=loan_data_strings.astype(dtype=int)

# Manipulating Numeric Data

In [90]:
#call the numeric data
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [91]:
#check for missing values in the dataset
np.isnan(np.isin(loan_data_numeric[:,0],temporary_fill)).sum()

0

### Substitute Filler Values

In [92]:
#call the first column in the header numeric
#header_numer

In [93]:
#examine the id column on the loan data numeric


since we filled our dataset with temporary fill, lets check to see if temporary fill is this column.
usually, the id column are usually non nullable

In [94]:
#call temporary_fill
temporary_fill

68616520.0

In [95]:
#check to  see if the temporary fill is in the id column


In [96]:
#lets get tthe sum to be sure


In [97]:
#call header numeric
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

For the loan_amt, int_rate, installment and total_payment, we will fill them with the maximum of the values in the columns while the funded amount will be filled with the minimum values of the column


In loan applications, the following terms mean:

- loan_amnt: The amount of money that the borrower is requesting to borrow.
- funded_amnt: The amount of money that the borrower was actually approved for and received.
- int_rate: The interest rate that the borrower will be charged on their loan.
- installment: The monthly payment that the borrower will make on their loan.
- total_pymnt: The total amount of money that the borrower will repay on their loan, including principal and interest.

When preprocessing data for a credit risk model, it is common to fill in missing values in the following way:

- For loan_amnt, int_rate, installment, and total_pymnt, fill in missing values with the maximum of the values in the columns. This is because a higher value for any of these variables indicates a higher risk of default.
- For funded_amnt, fill in missing values with the minimum of the values in the columns. This is because a lower funded_amnt indicates that the borrower was approved for a smaller loan amount, which suggests that they are less of a risk to the lender.

This approach to filling in missing values is justified by the fact that we are trying to build a credit risk model to predict the probability of default. By filling in missing values with the maximum or minimum values, we are erring on the side of caution and assuming that the borrower is a higher risk than they actually are. This will help to ensure that our model does not underestimate the risk of default and that we are able to accurately identify borrowers who are at risk of defaulting on their loans.

### Temporary Stats

In [98]:
#call temporary stats
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [99]:
#lets remove the  columns with nan or in this  case text values
temporary_stats[:,column_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

### Funded Amount

In [100]:
#call the funded amount in the header numeric
header_numeric[2]

'funded_amnt'

In [101]:
#examine the dataset in the loan numeric
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [102]:
#lets substitute the temporary fill in the funded amount wiht the nanmin in the column
loan_data_numeric[:,2]=np.where(loan_data_numeric[:,2]==temporary_fill,
                               temporary_stats[0,column_numeric[2]],
                               loan_data_numeric[:,2])

### Loaned Amount, Interest Rate, Total Payment and Installment

In [103]:
#call header numeric
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [104]:
#lets substitute the temporary_fill(missing values) with the maximum in each column. lets use a for loop
for i in [1,3,4,5]:
    loan_data_numeric[:,i]=np.where(loan_data_numeric[:,i]==temporary_fill,
                                   temporary_stats[2,column_numeric[i]],
                                loan_data_numeric[:,i])

In [105]:
#call the loan_numeric data
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

### Data Currency Change- The Exchange Rate

In [106]:
#import the eur_usd using the genfromtxt. set the dype to strings to see the column names 
eur_usd=np.genfromtxt("C:\\Users\\USER\\Downloads\\EUR-USD.csv",
                     delimiter=',',
                     autostrip=True,
                     dtype=str)
eur_usd

array([['Open', 'High', 'Low', 'Close', 'Volume'],
       ['1.2098628282546997', '1.2098628282546997', '1.11055588722229', '1.1287955045700073', '0'],
       ['1.1287955045700073', '1.1484194993972778', '1.117680549621582', '1.1205360889434814',
        '0'],
       ['1.119795799255371', '1.1240400075912476', '1.0460032224655151', '1.0830246210098267',
        '0'],
       ['1.0741022825241089', '1.1247594356536865', '1.0521597862243652', '1.1114321947097778',
        '0'],
       ['1.1215037107467651', '1.145304799079895', '1.0821995735168457', '1.0960345268249512',
        '0'],
       ['1.095902442932129', '1.1428401470184326', '1.0888904333114624', '1.122296690940857', '0'],
       ['1.1134989261627197', '1.1219995021820068', '1.081270456314087', '1.0939244031906128',
        '0'],
       ['1.0969001054763794', '1.1705996990203857', '1.0850305557250977', '1.1340054273605347',
        '0'],
       ['1.1225990056991577', '1.1460003852844238', '1.1089695692062378', '1.1255937814712524

The eur_usd contains the open, high, low, close and volume that was traded. The eur_usd represents the average monthly prices for dollar to eur for the year 2015. The close however, is the adjusted closing prices. We are  only interested in the closing prices however. so we have to import just that and skip the headers

In [107]:
#lets reimport the dataset, using the above conditions
eur_usd=np.genfromtxt("C:\\Users\\USER\\Downloads\\EUR-USD.csv",
                     delimiter=',',
                     autostrip=True,
                     skip_header=1,
                     usecols=[3])
eur_usd

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [108]:
#get the issue date column from the loan data strings
loan_data_strings[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

This contains all respective dates the loan was  issued. what we would do here, is tht we would  set the monthly numbers in loan_data_strings  to a variable exchange rates then replaces those months in exchange rates, with the close values in eur_usd

In [109]:
#set exchange rates to issue date  
exchange_rates=loan_data_strings[:,0]

In [110]:
#use a for loop to to iterate over all the months excluding month 0 which represents the missing values and store the monthly exchange rates
#for each month there
for i in range(1,13):
    exchange_rates=np.where(exchange_rates==i,
                          eur_usd[i-1],
                           exchange_rates)

now  we still have 0 in the exchnage rates which is the missing values or unaccounted issue date, lets store the mean of the yearly rates for the adjusted close

In [111]:
#use the np.where to store the mean for where it is 0.
exchange_rates=np.where(exchange_rates==0,
                       np.mean(eur_usd),
                       exchange_rates)

In [112]:
#lets store exchange rates to the dataset. first of all lets check to see that their shaoes are compatible
print('exchange_rates_shape',  exchange_rates.shape)
print("loan data Numeric shape:", loan_data_numeric.shape)

exchange_rates_shape (10000,)
loan data Numeric shape: (10000, 6)


Their shapes are incompatible, as exchange rates is 1d while loan data numeric is 2d, however, they have the same number of rows. so we have to reshape exchange rates so that it can become 2d and also be compatible.

In [113]:
#reshape the exchange rates to a 2d object
exchange_rates=np.reshape(exchange_rates,(10000,1))

In [114]:
#lets store the exchange rates in the loan data numeric dataset
loan_data_numeric=np.hstack((loan_data_numeric,exchange_rates))

In [115]:
#lets also ensure  that the exchange rate column is added to the header numeric.
header_numeric=np.concatenate((header_numeric,np.array(["exchange_rates"])))

### From USD to Eur

In [116]:
#lets call the header numeric
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt',
       'exchange_rates'], dtype='<U19')

we can see that from the header, loan  amount, funded amount, installment, total payment. are all in dollars therefore we have to chnage them to their Euro equivaluent for eachmonth of the application for the year 2015

In [117]:
#create a variable and store the columns we are interested in
column_dollars=[1,2,4,5]

In [118]:
#call loan_numeric, and pass the column index to it to be sure it actually gets you the columns you are interested in for conver
loan_data_numeric[:,column_dollars]

array([[35000.  , 35000.  ,  1184.86,  9452.96],
       [30000.  , 30000.  ,   938.57,  4679.7 ],
       [15000.  , 15000.  ,   494.86,  1969.83],
       ...,
       [10000.  , 10000.  ,  1372.97,  2185.64],
       [35000.  , 10000.  ,   354.3 ,  3199.4 ],
       [10000.  , 10000.  ,   309.97,   301.9 ]])

In [119]:
#get the exchange rates column from the loan data numeric
loan_data_numeric[:,-1]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

To convert values from dollars to euros using exchange rates, you should divide the dollar values by the exchange rate. This is because the exchange rate tells you how many euros you get for one dollar. So, to convert from dollars to euros, you need to divide the dollar value by the exchange rate.

- Exchange Rate: The exchange rate tells you how many euros you get for one dollar. For example, if the exchange rate is 0.85, it means you get 0.85 euros for each dollar.

- Conversion Formula: To convert a dollar amount to euros, you need to divide the dollar amount by the exchange rate. This is because you're essentially asking, "How many times does the exchange rate fit into the dollar amount?"

Euros = Dollars / Exchange Rate

In [120]:
#use a for loop to store the rates of the for each column. essentially we are adding new columns for every division.
for i in column_dollars:
    loan_data_numeric=np.hstack((loan_data_numeric,np.reshape(loan_data_numeric[:,i]/loan_data_numeric[:,-1],(10000,1))))

In [121]:
#call loan numeric and get the shape as well
loan_data_numeric.shape

(10000, 11)

We see that the new columns has been stored in the dataset, therefore, we have to attach the column names to the header numeric.


### Expanding the Header

In [122]:
#get the column names in header numeric for where the conversion has taken place and attach eur to the name.

header_additional=[column_name+"_USD" for column_name in header_numeric[column_dollars]]

In [123]:
#lets get concatenate the column names to the header numeric
header_numeric=np.concatenate((header_numeric,header_additional))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt',
       'exchange_rates', 'loan_amnt_USD', 'funded_amnt_USD', 'installment_USD', 'total_pymnt_USD'],
      dtype='<U19')

In [124]:
#lets make our headers more distinct. store the other columns with dollar names
header_numeric[column_dollars]=[column_name + "_EUR" for column_name in header_numeric[column_dollars]]
header_numeric

array(['id', 'loan_amnt_EUR', 'funded_amnt_EUR', 'int_rate', 'installment_EUR', 'total_pymnt_EUR',
       'exchange_rates', 'loan_amnt_USD', 'funded_amnt_USD', 'installment_USD', 'total_pymnt_USD'],
      dtype='<U19')

Now it looks better, however, it can be imporved  Lets store the usd and eur side by side. The best way to achieve this, is through a list, as there is no elegant way to achieve this.

In [125]:
#get the columns index order that will be side by side to each other.  the exchange rates should be last
column_index_sort_order=[0,1,7,2,8,3,4,9,5,10,6]

In [126]:
#pass the column index order as an index to header numeric
header_numeric[column_index_sort_order]

array(['id', 'loan_amnt_EUR', 'loan_amnt_USD', 'funded_amnt_EUR', 'funded_amnt_USD', 'int_rate',
       'installment_EUR', 'installment_USD', 'total_pymnt_EUR', 'total_pymnt_USD',
       'exchange_rates'], dtype='<U19')

In [127]:
#lets overwrite it and make it permanent
header_full=header_numeric[column_index_sort_order]

In [128]:
#lets repeat the same thing for loan_data. pass the column index order to loan data numeric
loan_data_numeric[:,column_index_sort_order]

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,        8.74,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,        5.51,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,        4.48,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,        1.79,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,        2.87,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,        1.06,        1.09]])

In [129]:
#overwite the loan data numeric use the column index order as index
loan_data_numeric=loan_data_numeric[:,column_index_sort_order]

In [130]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,        8.74,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,        5.51,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,        4.48,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,        1.79,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,        2.87,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,        1.06,        1.09]])

### Interest Rate

In [131]:
#call the interest rate column on the header numeric
header_numeric

array(['id', 'loan_amnt_EUR', 'funded_amnt_EUR', 'int_rate', 'installment_EUR', 'total_pymnt_EUR',
       'exchange_rates', 'loan_amnt_USD', 'funded_amnt_USD', 'installment_USD', 'total_pymnt_USD'],
      dtype='<U19')

In [132]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

We see that the interest rates are percentages for the rates charged to loan applicants. however this interest rates  are between 1 -100, convention dictates the interest rates are between 0 and 1  for ease of analysis.


In [133]:
#convert it to decimals between 0 and 1
loan_data_numeric[:,5]/100

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

In [134]:
#call the interest rates column to be sure
loan_data_numeric[:,5]=loan_data_numeric[:,5]/100

### Merging and Completing the Dataset

before we merge the both datasets, we have to ensure that they have compatible  shapes.

In [135]:
#check the shape of the string dataset
loan_data_strings.shape

(10000, 6)

In [136]:
#check for the shape of the numeric dataset
loan_data_numeric.shape

(10000, 11)

both datasets, contains the same number of rows, which means that we can stack them side by side

In [140]:
#we can merge them together, using the hstack or by concatenating the dataste
np.hstack((loan_data_numeric,loan_data_strings))

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [141]:
#store the stacked array in the loan_data variable
loan_data=np.hstack((loan_data_numeric,loan_data_strings))

In [142]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [144]:
#lets check for missing values once more, to be sure we ave treated them accordingly.
np.isnan(loan_data).sum()

0

In [145]:
#lets merge the headers toggether
np.concatenate((header_numeric,header_strings))

array(['id', 'loan_amnt_EUR', 'funded_amnt_EUR', 'int_rate', 'installment_EUR', 'total_pymnt_EUR',
       'exchange_rates', 'loan_amnt_USD', 'funded_amnt_USD', 'installment_USD', 'total_pymnt_USD',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [146]:
#store the merged headers and store them in a variable.
header_full=np.concatenate((header_numeric,header_strings))

### Sorting the Dataset

In [148]:
#lets sort thhe dataset, based on the first column which is id
np.sort(loan_data[:,0])

array([  373332.,   575239.,   707689., ..., 68614880., 68615915., 68616519.])

In [149]:
#lets use the argsort function as an index of the loan_data
loan_data[np.argsort(loan_data[:,0])]

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       36.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [150]:
#lets store the values in the loan_data
loan_data=loan_data[np.argsort(loan_data[:,0])]

In [151]:
#to be sure it has been sorted, we can use the argort the indices that will sort the array
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

### Storing the Dataset

In [152]:
#merge the header with the rest of the dataset
np.vstack((header_full,loan_data))

array([['id', 'loan_amnt_EUR', 'funded_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'state_address'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '36.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

We see that the dataset is now in the strings format, this is because the stacking function requires a unified data type

In [153]:
#lets store the above in a variable
loan_data=np.vstack((header_full,loan_data))

In [157]:
#lets save the file to an external eenvironment
np.savetxt("loan-data-Preprocessed.csv",loan_data,fmt='%s',delimiter=",")

Now we have cleaned, preprocessed and Transformed the Dataset, now the data science team can use this dataset to build a Credit Risk Model that predicts the probability of default.